In [40]:
import yfinance as yf
import pandas as pd

In [41]:
def gen_dataset(ticker_pair, start_date, end_date):
    dataset = []
    for pair in ticker_pair:
        ticker_data = {}
        data = yf.download(tickers=pair, start=start_date, end=end_date)
        for col in data.columns:
            ticker_data['currency'] = [pair]*len(data)
            ticker_data['date'] = data[col].index
            ticker_data[col[0]] = data[col].values
        ticker_df = pd.DataFrame(ticker_data)
        
        dataset.append(ticker_df)

    dataset_df = pd.concat(dataset, ignore_index=True)

    return dataset_df

In [42]:
start_date = '2015-01-05'
end_date = '2024-12-28'
pairs = ['EURUSD=X', 'VND=X', 'BTC-USD']
dataset_df = gen_dataset(ticker_pair=pairs, start_date=start_date, end_date=end_date)
dataset_df.loc[dataset_df['currency']=='EURUSD=X', 'currency'] = 'EUR-USD'
dataset_df.loc[dataset_df['currency']=='VND=X', 'currency'] = 'USD-VND'
dataset_df

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

,currency,date,Close,High,Low,Open,Volume
0,EUR-USD,2015-01-05,1.194643,1.197590,1.188909,1.195500,0
1,EUR-USD,2015-01-06,1.193902,1.197000,1.188693,1.193830,0
2,EUR-USD,2015-01-07,1.187536,1.190000,1.180401,1.187479,0
3,EUR-USD,2015-01-08,1.183600,1.184806,1.175601,1.183894,0
4,EUR-USD,2015-01-09,1.179607,1.183830,1.176831,1.179426,0
...,...,...,...,...,...,...,...
8846,BTC-USD,2024-12-23,94686.242188,96416.210938,92403.132812,95099.390625,65239002919
8847,BTC-USD,2024-12-24,98676.093750,99404.062500,93448.015625,94684.343750,47114953674
8848,BTC-USD,2024-12-25,99299.195312,99478.750000,97593.468750,98675.914062,33700394629
8849,BTC-USD,2024-12-26,95795.515625,99884.570312,95137.882812,99297.695312,47054980873
8850,BTC-USD,2024-12-27,94164.859375,97294.843750,93310.742188,95704.976562,52419934565

In [43]:
dataset_df.to_csv('yfinance_data.csv', index=False)